name: 新機能の開発
description: 新機能の開発
title: '✨ feature: '
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 新機能の概要を記載してください
    validations:
      required: true
  - type: input
    id: goal
    attributes:
      label: 完了の定義
      description: 完了の定義を記載してください
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: タスク
      description: 開発する上でのタスクを記載してください
      value: |
        - [ ]
        - [ ]
    validations:
      required: true
  - type: textarea
    id: module
    attributes:
      label: 追加するモジュール
      description: 開発で追加するモジュールを記載してください
      value: |
        - 
        - 
  - type: textarea
    id: note
    attributes:
      label: 備考
      description: 新機能の開発に関する備考を記載してください
